server:
  port: 4396
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/graduate_design
    username: root
    password: 15216252635zl
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.study.springDesign.pojo
  mapper-locations: classpath:com/study/springDesign/mapper/*.xml
